# -*- coding: utf-8 -*-
# Copyright 2019-2020 Lovac42
# Copyright 2014 Patrice Neff
# Copyright 2006-2019 Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
# Support: https://github.com/lovac42/Blitzkrieg


from .lib.com.lovac42.anki.version import POINT_VERSION

from .lib.com.lovac42.anki.others import safety_first

if POINT_VERSION < 10: #exact version unknown
    print("\n\nYou can't expect Blitzkrieg to run on this old version an Anki?!\n\n")

else:
    #Generated by build script
